spring.application.name=hotel
server.port=8060

spring.datasource.url=jdbc:mysql://localhost:3406/hotel_db
spring.datasource.username=root
spring.datasource.password=root

# Hibernate DDL Auto (create, update, validate, none)
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:changelog/db.changelog-master.xml

# Activer les logs SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Email
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Open Telemetry
otel.service.name=hotel
otel.exporter.otlp.endpoint=http://localhost:4318

management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.step=10s
management.endpoints.web.exposure.include=health,info,metrics
management.metrics.tags.application=${spring.application.name}